# -----------------------------------------------------------------------------
# Site Configuration for Theophilus Eriata
# -----------------------------------------------------------------------------

baseURL: "/"
languageCode: "en-us"
title: "Theophilus Eriata"
theme: ["PaperMod", "hugo-shortcode-gallery"]

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 10

taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: About
      url: "/about/"
      weight: 2
    - name: Leadership
      url: "/leadership/"
      weight: 3
    - name: Projects
      url: "/projects/"
      weight: 4
    - name: Blog
      url: "/blog/"
      weight: 5
    - name: Contact
      url: "/contact/"
      weight: 6

params:
  author: "Theophilus Eriata"
  description: "Undergraduate Computer Science (Honours) student at University of Calgary, specializing in Graphics, Robotics, DevOps, and Real-Time Systems."
  googleAnalyticsID: "G-PVVE70X9RZ"
  DateFormat: "2006-01-02"

  defaultTheme: "light"
  disableThemeToggle: false
  hideFooter: false

  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  disableScrollToTop: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowToc: false
  ShowWordCount: false
  ShowAllPagesInArchive: false

  math: true
  comments: false
  TocOpen: true
  UseHugoToc: true

  MainSections: ["about","skills","experience","projects","leadership","awards","blog"]

  profileMode:
    enabled: true
    title: "Theophilus Eriata"
    subtitle: "A passionate Computer Scientist and multidisciplinary engineer with experience spanning graphics programming, embedded systems, robotics, and full-stack development. I specialize in high-performance software, real-time rendering engines, and robotics frameworks, from low-level optimization to large-scale application design. With a strong academic foundation and a knack for mentorship, I bring technical precision, creative problem-solving, and collaborative leadership to every project I take on."
    imageUrl: "images/avatars/theophiluse.jpg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: About Me
        url: /about/
      - name: Projects
        url: /projects/
      - name: Blog
        url: "/blog/"
      - name: Contact
        url: "/contact/"
      - name: Tags
        url: tags/
      - name: Archive
        url: /archive/

  socialIcons:
    - name: Email
      url: "mailto:theophiluse@xiitechnologies.com"
    - name: GitHub
      url: "https://github.com/TheophilusE"
    - name: GitLab
      url: "https://gitlab.com/TheophilusE"
    - name: LinkedIn
      url: "https://linkedin.com/in/theophilus-eriata"
    - name: YouTube
      url: "https://www.youtube.com/@Theophilus-E"
    - name: X
      url: "https://x.com/TheophilusE12"
    - name: Itch.io
      url: https://theophiluse.itch.io
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=Theophilus+Eriata

  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Theophilus Eriata"
    icon: "favicon.ico"
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: "autumn"
  tableOfContents:
    startLevel: 2
    endLevel: 2
    ordered: false
