title = "Theophilus Eriata"

theme = "coder"

languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

paginate = 20
canonifyURLs = true

enableEmoji = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]
author = "Theophilus Eriata"
avatarURL = "images/avatar.jpg"
images = ["images/og_cover.png"]
description = "Personal site for public interface"
keywords = "TheophilusEriata,Blog,Mathematics,SoftwareDevelopment,C++,Java,Python,FTC"
info = "Computer Scientist"

since = 2022
dateFormat = "2006-01-02"

colorScheme = "auto"
hideColorSchemeToggle = false

customCSS = ["css/custom.css", "css/syntax.css"]
customJS = []
customRemoteJS = []

[params.googleTagManager]
id = "G-PVVE70X9RZ"

[params.goatCounter]
code = "theophiluse72"

[params.utterances]
repo = "TheophilusE/TheophilusE.dev"
issueTerm = "pathname"
theme = "github-dark"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/theophilus-eriata-a58425234/"

[[params.social]]
name = "GitHub"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://github.com/TheophilusE/"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Categories"
weight = 3
url = "categories/"
