title = "Theophilus Eriata"

theme = "coder"

languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

paginate = 20
canonifyURLs = true

enableEmoji = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]
author = "Theophilus Eriata"
avatarURL = "images/avatar.jpg"
images = ["images/og_cover.png"]
description = "Personal site for public interface"
keywords = "Blog,SoftwareDevelopment,C++,Java,Python"
info = "Software Developer"

dateFormat = "2006-01-02"

colorScheme = "dark"
hideColorSchemeToggle = true

customCSS = ["css/custom.css", "css/syntax.css"]

[params.goatCounter]
code = "theophiluse72"

[params.utterances]
repo = "TheophilusE/TheophilusE.github.io"
issueTerm = "pathname"
theme = "github-dark"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/TheophilusE/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/theophilus-eriata-a58425234/"

[[menu.main]]
name = "About"
weight = 1
url = "about/"
