[build]
publish = "public"
command = "hugo --gc --minify --baseURL $URL"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "https://theophiluse-website.netlify.com/*"
to = "https://theophilus.dev/:splat"
status = 301
force = true

[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/pt-br/*"
to = "/pt-br/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/en/404.html"
status = 404
