[build]
publish = "public"
command = "hugo --gc --minify --baseURL $URL"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# [context.deploy-preview]
# command = "hugo --buildFuture --buildDrafts --baseURL $URL"

