[build]
  publish = "public"
  command = "hugo --gc --minify --baseURL $URL"
  environment = { HUGO_VERSION = "0.148.2", HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true" }

[context.production.environment]
  HUGO_VERSION = "0.148.2"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.148.2"
  NODE_ENV = "development"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.148.2"
  NODE_ENV = "development"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
